### ISSUE TITLE
Add Hello World example of ViewModel & XAML Binding

### ISSUE THREAD

**Issue by timgabrhel** [gatewayapps/apptemplate-8.1#5]
A basic example that shows a view binding back to the view model using any necessary Prism/Unity constructs.

**Comment by timgabrhel** [comment]
I noticed the MainPageViewModel is already present, but I had to "Include in Project" to see it in Visual Studio.

**Comment by timgabrhel** [comment]
Created a pull request with the changes. It's my first PR. I think I did it right.

**Comment by johnmurphy01** [comment]
Cool, thanks!
